# Generated by Django 5.0.2 on 2024-02-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misiBackend', '0003_clientevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
